# base image
FROM node:12.2.0-alpine

# set working directory
WORKDIR /myServer

# add `/app/node_modules/.bin` to $PATH
ENV PATH /myServer/node_modules/.bin:$PATH

COPY myServer /myServer

# install and cache app dependencies
RUN yarn install --silent

# start app
CMD ["yarn", "start"]