version: '3.7'
services: 
  my-phone-catalogue-server:
    build: 
      context: .
      dockerfile: Dockerfile-server
    ports:
      - "4000:4000"
  my-phone-catalogue-dev:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - '.:/app'
      - '/app/node_modules'
