export const FETCH_PHONES = "FETCH_PHONES";
export const FETCH_PHONES_SUCESS = "FETCH_PHONES_SUCESS";
export const SET_PHONE_SELECTED = "SET_PHONE_SELECTED";
export const RESET_PHONE_SELECTED = "RESET_PHONE_SELECTED";
